### ISSUE TITLE
Predefined value of LHCI_BUILD_CONTEXT__CURRENT_BRANCH

### ISSUE THREAD

**Issue by primko** [GuruCharan94/azure-devops-extensions#13]
Hi, I'm starting to use you extensions, but I have a problem with this
`this.LHCI_BUILD_CONTEXT__CURRENT_BRANCH = tasklib.getVariable('BUILD_SOURCEBRANCHNAME');`
[lighthouse-ci/lighthouse-ci-build-task/src/lighthouse-ci-build-context.ts](url)
I'd like to make it easy to control because it's not triggered by commits. I  use the '**Build.SourceBranchName'** override for now, but
`##[warning]Overwriting readonly task variable 'Build.SourceBranchName'. This behavior will be disabled in the future.`

**Comment by GuruCharan94** [comment]
`I'd like to make it easy to control because it's not triggered by commits. I use the  'Build.SourceBranchName' override for now`. 

Can you share any information on your pipeline?
- How is is triggered?
- Is it a build or a release pipeline? 
- What is the version control used?  
- Logs of failure with private information removed?
- What do you override this with?

I would like to understand your usage first and then figure out a solution to allow more control to the users

**Comment by primko** [comment]
- it is manual periodical build
- Azure Repos Git
- I don't have failure, only warning `Overwriting readonly task variable 'Build.SourceBranchName'`

I want to manually run the build with LHCI parameters and set variables to pipeline
`echo "##vso[task.setvariable variable=Build.SourceBranchName]$(version)"
echo "##vso[task.setvariable variable=LHCI_BUILD_CONTEXT__CURRENT_HASH]${HASH}"
echo "##vso[task.setvariable variable=LHCI_BUILD_CONTEXT__COMMIT_TIME]${TIME}"
    echo "##vso[task.setvariable variable=LHCI_BUILD_CONTEXT__CURRENT_BRANCH]$(version)"
    echo "##vso[task.setvariable variable=LHCI_BUILD_CONTEXT__COMMIT_MESSAGE]Periodic run"`

**echo "##vso[task.setvariable variable=Build.SourceBranchName]$(version)** - give rise to a warning, definition of the **LHCI_BUILD_CONTEXT__CURRENT_BRANCH** has no effect, I always get in the report value from **Build.SourceBranchName**

**Comment by GuruCharan94** [comment]
If I understand correctly, you are requesting that if there are LHCI* pipeline variables defined by the user, then the task should use them as default and when these variables are not available, the task should use the current behaviour.

Am I right? If yes, do you want to send in a pull request ?

**Comment by primko** [comment]
yes, you are right
about a pull request - not for now, but if you don't have a time too, I will try to make sense of it
