### ISSUE TITLE
REGARDING PWA

### ISSUE THREAD

**Issue by ravindrainduri** [GuruCharan94/azure-devops-extensions#29]
Hi Charan,

Why is the PWA score not visible while the scan results are published at the end of the pipeline , could you please explain why it is.

Kind Regards
Ravindra Induri

**Comment by GuruCharan94** [comment]
Hi, Which extension are you talking about and please provide as much details as possible about what you are trying to achieve. Logs, task configuration etc would be useful.

**Comment by ravindrainduri** [comment]
Hi Charan,

We could see couple of 503 's in our light house scan 
![image](https://user-images.githubusercontent.com/45281912/151531929-1d674883-e3a1-4b39-bb75-9e420e1983df.png)
and we are passing the target url as follows to glh scan plugin 
 - task: googlelighthouse@0
    inputs:
      targetURL: 'http://$(json.stagingDomainName)'
      parameters: '--emulated-form-factor desktop --disable-storage-reset --throttling-method provided'
Note : After getting this 503's for couple of times , we are rerunning the failed jobs then  it is working fine, Could you please kindly help here .

**Comment by ravindrainduri** [comment]
> Hi, Which extension are you talking about and please provide as much details as possible about what you are trying to achieve. Logs, task configuration etc would be useful.

Hi Again Charan,

![image](https://user-images.githubusercontent.com/45281912/151533936-c673fd09-2630-494f-98b4-eafe3d11ff9d.png)
We could see the glh scan results getting generated at the end of the scan but when we are transferring the scan results we are not able the PWA score properly from azure devops pipeline to mulesoft API as part of glh scan job status update.  Could you please help here how to get PWA score trasnferred or embedded in the API .

**Comment by GuruCharan94** [comment]
The first screenshot tells me that the site is returning a 503 status code. The 503 looks like a problem with the site and not lighthouse or the extension.

The 2nd screenshot is a scan of *my website*. My site is not a PWA and therefore would obviously show no results for that section of the scan. 

Both these problems are not related to the extension or even lighthouse for that matter, Closing the issue.

**Comment by ravindrainduri** [comment]
Hi Charan, 

Thanks again for the help and one last query ,how may we know whether our site is PWA or not , Could you please explain.
